language: C

install:
  - travis_wait ./setup/travis_install.sh lsst-sims nose pandas pylint
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - pip install coveralls
  - setup lsst_sims
  - eups declare -r . {{cookiecutter.repo_name|lower}} -t current
  - setup {{cookiecutter.repo_name|lower}}

cache:
  directories:
  - $HOME/miniconda.tarball
  timeout: 600

script:
  - nosetests --with-coverage --cover-package=desc.{{cookiecutter.repo_name|lower}}
#  - pylint --py3k `find . -name \*.py -print`
#  - pylint --rcfile=.pylintrc `find . -name \*.py -print`

after_success:
  - coveralls
